# -*- coding: utf-8 -*-
"""OEL Final Robust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buDW5YUXMqRyISBo9KDpPebbqRMLTe9B
"""

!pip install -q ultralytics opencv-python numpy matplotlib

import cv2
import numpy as np
import matplotlib.pyplot as plt
import time
import json

from google.colab.patches import cv2_imshow
from google.colab import files
from ultralytics import YOLO

THRESHOLD = 869        # classical pixel-count cutoff (fallback method)
CONF      = 0.10       # YOLO confidence (0.35 - 0.55)
METHOD    = "yolo"      # "yolo" (robust) or "classical" (fast, no GPU)

VIDEO_PATH = None       # set after upload in the next cell
print(f"Method = {METHOD} | Threshold = {THRESHOLD} | YOLO confidence = {CONF}")

uploaded = files.upload()
VIDEO_PATH = "/content/" + list(uploaded.keys())[0]
print("Using video:", VIDEO_PATH)

cap = cv2.VideoCapture(VIDEO_PATH)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps_video = cap.get(cv2.CAP_PROP_FPS)

# Jump to a few seconds before the end instead of using frame 0
SECONDS_FROM_END = 5
target_frame = max(total_frames - int(SECONDS_FROM_END * fps_video), 0)
cap.set(cv2.CAP_PROP_POS_FRAMES, target_frame)

ok, frame = cap.read()
cap.release()

if not ok:
    raise RuntimeError("Could not read the video — check the file uploaded correctly.")

print("Opened:", ok, "| total frames:", total_frames, "| native fps:", round(fps_video, 2))
print(f"Grabbed frame {target_frame} (~{SECONDS_FROM_END}s from end)")
print("Frame size:", frame.shape)
cv2_imshow(frame)

def make_row_rois(x_start, x_end, y_start, y_end, n_cols):
    xs = np.linspace(x_start, x_end, n_cols + 1)
    return [
        np.array([[int(xs[i]), y_start], [int(xs[i+1]), y_start],
                   [int(xs[i+1]), y_end], [int(xs[i]), y_end]], dtype=np.int32)
        for i in range(n_cols)
    ]

X_START, X_END = 0, 1030      # exclude trees/road on the right
N_COLS = 22                    # spots per row band — tune to match line spacing

# (y_start, y_end) per row band — tune these against the overlay below
Y_BANDS = [
    (0,   95),
    (100, 215),
    (215, 330),
    (330, 445),
    (445, 560),
]

rois = []
for y0, y1 in Y_BANDS:
    rois += make_row_rois(X_START, X_END, y0, y1, N_COLS)

vis = frame.copy()
for i, roi in enumerate(rois, start=1):
    cv2.polylines(vis, [roi], True, (255, 0, 0), 2)
    cx, cy = int(roi[:, 0].mean()), int(roi[:, 1].mean())
    cv2.putText(vis, str(i), (cx - 8, cy), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 255), 1)
cv2_imshow(vis)
print(f"{len(rois)} slot ROIs defined.")

def preprocess(frame, blur_kernel=(5, 5), block=25, c=16):
    gray    = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, blur_kernel, 0)
    binary  = cv2.adaptiveThreshold(
        blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV, block, c)
    kernel  = np.ones((3, 3), np.uint8)
    binary  = cv2.dilate(binary, kernel, iterations=2)
    return gray, blurred, binary

def count_white(binary, roi):
    mask = np.zeros(binary.shape, dtype=np.uint8)
    cv2.fillPoly(mask, [roi], 255)
    return cv2.countNonZero(cv2.bitwise_and(binary, mask))

gray, blurred, binary = preprocess(frame)
fig, ax = plt.subplots(1, 3, figsize=(16, 5))
ax[0].imshow(gray,    cmap="gray"); ax[0].set_title("1. Grayscale")
ax[1].imshow(blurred, cmap="gray"); ax[1].set_title("2. Gaussian Blur")
ax[2].imshow(binary,  cmap="gray"); ax[2].set_title("3. Adaptive Threshold + Dilation")
for a in ax: a.axis("off")
plt.tight_layout(); plt.show()

model = YOLO("yolov8n.pt")
VEHICLES = {2: "car", 5: "bus", 7: "truck"}

def point_in_any_roi(cx, cy, rois):
    for i, roi in enumerate(rois):
        if cv2.pointPolygonTest(roi, (float(cx), float(cy)), False) >= 0:
            return i
    return -1

def yolo_occupancy(frame, rois, conf=0.25, imgsz=1280, debug=False):
    results = model(frame, conf=conf, imgsz=imgsz, verbose=False)[0]
    occupied = [False] * len(rois)
    detections = []
    for box in results.boxes:
        cls = int(box.cls[0])
        if cls not in VEHICLES:
            continue
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cx, cy = (x1 + x2) // 2, (y1 + y2) // 2
        idx = point_in_any_roi(cx, cy, rois)
        if idx >= 0:
            occupied[idx] = True
        detections.append((x1, y1, x2, y2, VEHICLES[cls], float(box.conf[0])))

    if debug:
        print(f"Raw boxes returned by model: {len(results.boxes)} | "
              f"vehicle-class boxes: {len(detections)}")
        if len(results.boxes) and not detections:
            seen_classes = sorted(set(int(b.cls[0]) for b in results.boxes))
            print(f"  Model detected classes {seen_classes} — none matched VEHICLES {list(VEHICLES)}. "
                  f"Try lowering conf further or check the model file.")

    return occupied, detections

CONF = 0.25   # lowered from 0.45 — aerial cars are small/low-confidence

t0 = time.time()
occupied, detections = yolo_occupancy(frame, rois, conf=CONF, imgsz=1280, debug=True)
yolo_fps = 1.0 / (time.time() - t0)

overlay = frame.copy()
for roi, occ in zip(rois, occupied):
    color = (0, 0, 255) if occ else (0, 255, 0)
    cv2.polylines(overlay, [roi], True, color, 2)
for (x1, y1, x2, y2, label, dconf) in detections:
    cv2.rectangle(overlay, (x1, y1), (x2, y2), (255, 200, 0), 1)

free = sum(1 for o in occupied if not o)
cv2.rectangle(overlay, (8, 8), (260, 70), (0, 0, 0), -1)
cv2.putText(overlay, f"Free: {free}/{len(rois)}", (16, 34), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
cv2.putText(overlay, f"YOLO | {yolo_fps:.1f} FPS", (16, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)
cv2_imshow(overlay)
print(f"Free: {free}/{len(rois)} | vehicles detected: {len(detections)}")

def classical_occupancy(binary, rois, threshold):
    occupied = []
    for roi in rois:
        area = cv2.contourArea(roi)
        px = count_white(binary, roi)
        occupied.append((px / max(area, 1)) > (threshold / 3000.0))
    return occupied

occ_classical = classical_occupancy(binary, rois, THRESHOLD)
free_c = sum(1 for o in occ_classical if not o)
print(f"Classical method — Free: {free_c}/{len(rois)}")

N = 30
cap = cv2.VideoCapture(VIDEO_PATH)
t0 = time.time()
for _ in range(N):
    ok, fr = cap.read()
    if not ok: break
    _, _, b = preprocess(fr)
    for roi in rois:
        count_white(b, roi)
classical_fps = N / (time.time() - t0)
cap.release()

cap = cv2.VideoCapture(VIDEO_PATH)
t0 = time.time()
for _ in range(N):
    ok, fr = cap.read()
    if not ok: break
    yolo_occupancy(fr, rois)
yolo_fps_bench = N / (time.time() - t0)
cap.release()

print("=" * 40)
print(f"Classical pixel-counting : {classical_fps:6.2f} FPS")
print(f"YOLOv8n detection        : {yolo_fps_bench:6.2f} FPS")
print("=" * 40)

out_path = "/content/smartpark_annotated.mp4"
fourcc = cv2.VideoWriter_fourcc(*"mp4v")

cap = cv2.VideoCapture(VIDEO_PATH)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps_video = cap.get(cv2.CAP_PROP_FPS)

# Process the middle 15 seconds instead of starting from frame 0
WINDOW_SECONDS = 15
window_frames = int(WINDOW_SECONDS * fps_video)
start_frame = max((total_frames - window_frames) // 2, 0)
end_frame = min(start_frame + window_frames, total_frames)

cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)
print(f"Processing frames {start_frame}-{end_frame} "
      f"(~{WINDOW_SECONDS}s centered in a {total_frames}-frame video)")

out = None
frames_written = 0
log = []

while (start_frame + frames_written) < end_frame:
    ok, frame = cap.read()
    if not ok:
        break

    t0 = time.time()
    if METHOD == "yolo":
        occupied, detections = yolo_occupancy(frame, rois, CONF, imgsz=1280)
    else:
        _, _, binary = preprocess(frame)
        occupied = classical_occupancy(binary, rois, THRESHOLD)
        detections = []
    fps = 1.0 / (time.time() - t0)

    free = 0
    for roi, occ in zip(rois, occupied):
        color = (0, 0, 255) if occ else (0, 255, 0)
        if not occ:
            free += 1
        cv2.polylines(frame, [roi], True, color, 2)

    cv2.rectangle(frame, (8, 8), (300, 78), (0, 0, 0), -1)
    cv2.putText(frame, f"Free slots: {free}/{len(rois)}", (16, 34),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
    cv2.putText(frame, f"{METHOD} | FPS: {fps:.1f}", (16, 62),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)

    if out is None:
        h, w = frame.shape[:2]
        out = cv2.VideoWriter(out_path, fourcc, fps_video, (w, h))
    out.write(frame)

    log.append({"frame": start_frame + frames_written, "free": free, "total": len(rois)})
    frames_written += 1

cap.release()
if out: out.release()
print(f"Saved {frames_written} annotated frames from the middle {WINDOW_SECONDS}s.")

with open("/content/occupancy_log.json", "w") as f:
    json.dump(log, f, indent=2)

files.download(out_path)
files.download("/content/occupancy_log.json")
